openapi: 3.0.3
info:
  title: API de la Libreria ICPF
  description: |-
    Documentación de la API de la librería ICPF que proporciona endpoints para la gestión de libros, autores, categorias, pedidos y estadísticas.
    
    Incluye especificaciones detalladas para autenticación, operaciones CRUD y consultas avanzadas.
    
  contact:
    email: jonathancanofreta@gmail.com
  license:
    name: Licencia MIT 
    url: https://opensource.org/license/mit
  version: 1.0.0
servers:
  - url: https://icpf-api-production.up.railway.app/
    description: Servidor Railway
tags:
  - name: libros
    description: Acceso a los métodos CRUD de libros
paths:
  /libros:
    get:
      tags:
        - libros
      summary: Obtener todos los libros
      description: Con el metodo GET /libros puedes obtener todos los libros disponibles en la librería
      operationId: getLibros
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Libros'          
        '400':
          description: Solicitud incorrecta
      #security:
        #- petstore_auth:
            #- write:pets
            #- read:pets
    post:
      tags:
        - libros
      summary: Crea un nuevo Libro
      description: Con el método **POST "/libros"** se puede crear un nuevo libro.
      operationId: crearLibro
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  description: Título del nuevo libro
                descripcion:
                  type: string
                  description: Descripción del nuevo libro
                precio:
                  type: number
                  format: float
                  description: Precio del nuevo libro con 2 decimales
                  example: 22.21
                cantidad:
                  type: integer
                  format: int64
                  description: Cantidad en stock del nuevo libro
                  example: 2
                paginas:
                  type: integer
                  format: int64
                  description: Cantidad de páginas del nuevo libro
                  example: 201
                imagen:
                    type: string
                    format: binary
              required:
                - titulo
                - descripcion
                - precio
                - cantidad
                - paginas
                - imagen
      responses:
        '201':
          description: Libro Creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Libros'   
        '400':
          description: Solicitud Incorrecta
      security:
        - petstore_auth:
            - write:pets
            - read:pets
  /libros/{libroID}:
    get:
      tags:
        - libros
      summary: Obtener información de un libro por su ID
      description: Con el método GET /libros/:id puedes obtener la información del libro correspondiente al ID proporcionado.
      operationId: getLibrosById
      parameters:
        - name: libroID
          in: path
          description: ID del libro del que se quieren obtener los datos
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Libros'          
        '400':
          description: Solicitud incorrecta
  /libros/buscar:
    get:
      tags:
        - libros
      summary: Buscador de libros por título
      description: Con el método GET "/libros/buscar?titulo=TITULO_LIBRO" puedes buscar un libro por su título.
      operationId: buscarLibros
      parameters:
        - name: titulo
          in: query
          description: ID del libro del que se quieren obtener los datos
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Libros'          
        '400':
          description: Solicitud incorrecta
  /libros/columna:
    get:
      tags:
        - libros
      summary: Obtiene todos los libros filtrados y ordenados
      description: Con el método GET "/libros/buscar?titulo=TITULO_LIBRO" puedes buscar un libro por su título.
      operationId: librosColumna
      parameters:
        - name: columna
          in: query
          description: Columna que se quiere ordenar. Se debe escoger entre **"l.titulo"**, **"l.precio"**, **"l.cantidad"**, o **"l.paginas"**
          required: true
          schema:
            type: string
        - name: tipo
          in: query
          description: Orden del filtro. Se debe escoger entre **"ASC"** o **"DESC"**
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Libros'          
        '400':
          description: Solicitud incorrecta
components:
  schemas:
    Libros:
      type: object
      properties:
        libro_id:
          type: integer
          format: int64
          example: 10
        libro_titulo:
          type: string
          example: Panorama del Antiguo Testamento
        libro_descripcion:
          type: string
          example: Este es un libro que recorre teológica e historicamente el relato del Antiguo Testamento...
        libro_precio:
          type: integer
          format: int64
          example: 25.34
        libro_cantidad:
          type: integer
          example: 4
        libro_paginas:
          type: integer
          format: int64
          example: 465
        libro_imagen:
          type: string
          example: https://iguiskudllwluojaxepj.supabase.co/storage/v1/object/public/icpf-imagenes/libros/...